const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.scrollto,
		C3.Behaviors.Fade,
		C3.Behaviors.Timer,
		C3.Behaviors.Sin,
		C3.Plugins.Arr,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Spritefont2.Exps.LayerName,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Exps.At,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.max,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Acts.SetSize
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{JSON: 0},
	{Browser: 0},
	{Touch: 0},
	{Mouse: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{Tween: 0},
	{bg_ui: 0},
	{btnMenu: 0},
	{btnReset: 0},
	{btnSound: 0},
	{defeat: 0},
	{win: 0},
	{nMoves: 0},
	{target: 0},
	{ScrollTo: 0},
	{gamemanager: 0},
	{bg_game: 0},
	{remove: 0},
	{FadeIn: 0},
	{FadeOut: 0},
	{hand: 0},
	{posX: 0},
	{posY: 0},
	{OccupiedByPair: 0},
	{Blocked: 0},
	{type: 0},
	{color: 0},
	{Tile: 0},
	{row: 0},
	{col: 0},
	{targetX: 0},
	{targetY: 0},
	{isMoving: 0},
	{locked: 0},
	{sticky: 0},
	{jump: 0},
	{Timer: 0},
	{Trio: 0},
	{Sine: 0},
	{tutorial: 0},
	{ui_stars: 0},
	{Variables: 0},
	{BoardArray: 0},
	{MatchArray: 0},
	{bgWin: 0},
	{btnPlay: 0},
	{bg_movements_win: 0},
	{win_stars: 0},
	{Bullet: 0},
	{Rotate: 0},
	{confeti_particles: 0},
	{transition: 0},
	{name: 0},
	{txtUI: 0},
	{bgSelector: 0},
	{btnArrowLeft: 0},
	{btnArrowRight: 0},
	{Nivel: 0},
	{btnNivel: 0},
	{nHoja: 0},
	{cam_selector: 0},
	{pageIndicator: 0},
	{txtBtnNivel: 0},
	{btnMoreGames: 0},
	{gameLogo: 0},
	{splashLogo: 0},
	{goGame: 0},
	{Fade: 0},
	{taptoplay: 0},
	{star_selector: 0},
	{star_selector_ui: 0},
	{Buttons: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{newlayer: 0},
	{GAMENAME_SAVE: 0},
	{TOTLEVELS: 0},
	{posXConfeti: 0},
	{posYConfeti: 0},
	{nLayer: 0},
	{selectedUID: 0},
	{isSwapping: 0},
	{swapSpeed: 0},
	{stars: 0},
	{selectedX: 0},
	{selectedY: 0},
	{nextX: 0},
	{nextY: 0},
	{selectedCol: 0},
	{selectedRow: 0},
	{newX: 0},
	{newY: 0},
	{newCol: 0},
	{newRow: 0},
	{newUID: 0},
	{isWin: 0},
	{totStars: 0},
	{LevelsLoaded: 0},
	{Level: 0},
	{TileSize: 0},
	{gap: 0},
	{Cols: 0},
	{Rows: 0},
	{StartX: 0},
	{StartY: 0},
	{CenterX: 0},
	{CenterY: 0},
	{BoardWidth: 0},
	{BoardHeight: 0},
	{ScaleElements: 0},
	{myColor: 0},
	{cantLocked: 0},
	{cantSticky: 0},
	{cantTrios: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	bg_ui: class extends self.ISpriteInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	btnReset: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	gamemanager: class extends self.ISpriteInstance {},
	bg_game: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	Tile: class extends self.ISpriteInstance {},
	Trio: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	ui_stars: class extends self.ISpriteInstance {},
	Variables: class extends self.IArrayInstance {},
	BoardArray: class extends self.IArrayInstance {},
	MatchArray: class extends self.IArrayInstance {},
	bgWin: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	bg_movements_win: class extends self.ISpriteInstance {},
	win_stars: class extends self.ISpriteInstance {},
	confeti_particles: class extends self.ISpriteInstance {},
	transition: class extends self.ISpriteInstance {},
	txtUI: class extends self.ISpriteFontInstance {},
	bgSelector: class extends self.ISpriteInstance {},
	btnArrowLeft: class extends self.ISpriteInstance {},
	btnArrowRight: class extends self.ISpriteInstance {},
	btnNivel: class extends self.ISpriteInstance {},
	cam_selector: class extends self.ISpriteInstance {},
	pageIndicator: class extends self.ISpriteInstance {},
	txtBtnNivel: class extends self.ISpriteFontInstance {},
	btnMoreGames: class extends self.ISpriteInstance {},
	gameLogo: class extends self.ISpriteInstance {},
	splashLogo: class extends self.ISpriteInstance {},
	taptoplay: class extends self.ISpriteInstance {},
	star_selector: class extends self.ISpriteInstance {},
	star_selector_ui: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {}
}